# Generated by Django 4.2.5 on 2023-09-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
