# Generated by Django 4.2.5 on 2023-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_college_school_schooldata_family_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='high_school_percentage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='intermidiate_percentage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
