# Generated by Django 4.2.5 on 2023-09-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_schooldata_contact_schooldata_high_school_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='caste',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('SC/ST', 'SC/ST'), ('OBC', 'OBC')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooldata',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooldata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schooldata',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
